/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/astryx/wildferretTheme.ts
 * Command: astryx theme build src/styles/astryx/wildferretTheme.ts --out src/styles/astryx/wildferret.theme.css
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const wildferretTheme: DefinedTheme;
